# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  chisel = {
    pname = "chisel";
    version = "e592a02b3ff085cca98bf5e69dec07409010cfeb";
    src = fetchFromGitHub {
      owner = "Emin017";
      repo = "chisel";
      rev = "e592a02b3ff085cca98bf5e69dec07409010cfeb";
      fetchSubmodules = false;
      sha256 = "sha256-vajfWgLTn8LepaPWAIl7rFE790x2oymA0Snc17UgXfE=";
    };
    date = "2025-02-07";
  };
}
